import { Theme } from '@/types'

/**
 * @name 游戏模板配置
 * @description 用于约束生成图像符合2D横版像素风游戏的提示词模板（包含正向提示词和反向提示词）
 */
export const GAME_TEMPLATES = {
  // 正向提示词模板
  positive: {
    character: '2D side-scrolling pixel art character, 16-bit retro style, high contrast colors, hand-drawn texture, dynamic lighting effects, razor-sharp pixel outline, ultra-bold character silhouette, crystal-clear edge definition, complete full body sprite from head to feet, roguelike design, facing right direction, perfect right-facing side view profile pose, centered composition with proper proportions, standing upright posture, full character visible within frame, rich character details with intricate pixel art features, expressive character design with unique personality traits, detailed clothing and accessories that match the theme aesthetic, absolutely pure checkerboard background pattern with alternating light gray and white squares, completely isolated character sprite against checkerboard transparency grid, zero environmental contamination, no decorative elements, no props or objects, pristine sprite extraction with checkerboard background, no cropping or cut-off limbs, optimal game asset format with checkerboard transparency indicator, maximum contrast separation against checkerboard pattern, ultra-clean character boundaries on checkerboard grid, no adjacent objects, no surrounding elements, pure character focus on checkerboard background, isolated subject only against transparency checkerboard, minimal composition with checkerboard background pattern, character-only output on checkerboard grid, no contextual elements except checkerboard transparency pattern, sterile checkerboard isolation background, perfect checkerboard transparency grid background, clean cutout character sprite on checkerboard pattern',
    background: '2D side-scrolling pixel art background, horizontal scrolling composition, high saturation dark tones, hand-drawn texture, dynamic lighting, atmospheric depth, layered parallax elements, no characters',
    ground: '2D side-scrolling pixel art ground texture, horizontal cross-sectional side view, Dead Cells inspired visual style, hand-drawn pixel art appearance, organic pixel textures with subtle irregularities, rich color depth with careful shading, atmospheric pixel art lighting, detailed pixel craftsmanship, artisanal pixel work quality, painterly pixel art approach, sophisticated color gradients within pixel constraints, textural depth through pixel art techniques, DEAD CELLS AESTHETIC: moody atmospheric colors, rich pixel art depth, subtle texture variations, organic pixel imperfections, hand-crafted pixel quality, painterly digital art style, sophisticated pixel shading, atmospheric color palettes. ABSOLUTE PRIORITY: texture must completely fill 100% of the entire image area with zero empty space, zero margins, zero borders, extending to every single pixel edge with maximum coverage density. MATERIAL PURITY: strictly basic material elements only - simple soil layers, basic rock strata. COMPLETE ENVIRONMENTAL EXCLUSION: absolutely NO environmental objects, NO surface elements, NO decorative items, NO props, NO vegetation, NO plants, NO trees, NO grass, NO flowers, NO roots, NO structures, NO buildings, NO architecture, NO atmospheric effects, NO particles, NO dust, NO smoke, NO fog, NO weather effects, NO sky elements, NO clouds, NO lighting fixtures, NO torches, NO lamps, NO shadows, NO reflections, NO water bodies, NO fire effects, NO magical elements, NO ornamental details, NO surface decorations, NO contextual objects, NO scene elements, NO world objects, NO environmental interference, NO complex geological formations, NO mineral veins, NO detailed stratification, NO intricate layering. Pure basic material texture with maximum fill density, seamless tileable pattern, clean pixel art style, 16-bit retro aesthetic, minimal material composition',
    obstacle: '2D side-scrolling pixel art obstacle object, 16-bit retro style, Dead Cells inspired visual style, hand-drawn pixel art appearance, organic pixel textures with subtle irregularities, rich color depth with careful shading, atmospheric pixel art lighting, detailed pixel craftsmanship, artisanal pixel work quality, painterly pixel art approach, sophisticated color gradients within pixel constraints, textural depth through pixel art techniques, DEAD CELLS AESTHETIC: moody atmospheric colors, rich pixel art depth, subtle texture variations, organic pixel imperfections, hand-crafted pixel quality, painterly digital art style, sophisticated pixel shading, atmospheric color palettes, high contrast colors, hand-drawn texture. CRITICAL FRONT VIEW ENFORCEMENT: NEVER diagonal view, NEVER side view, NEVER three-quarter view, NEVER angled perspective, NEVER tilted view, NEVER rotated perspective, NEVER oblique angle, NEVER slanted orientation, NEVER perspective distortion, NEVER depth perspective, NEVER isometric view, MANDATORY FLAT FRONTAL VIEW with orthographic projection, EXCLUSIVELY straight-on direct view, ABSOLUTELY flat 2D presentation, zero perspective effects, completely flat frontal silhouette, pure orthogonal front projection. Simple blocking object with clean geometric form, solid structural design with clear boundaries, functional game collision asset, well-defined obstacle shape with balanced proportions, centered composition. Theme-adaptive visual style that harmonizes with current aesthetic without specific object references, contextually appropriate color palette and material textures that naturally integrate with theme atmosphere, design elements that feel cohesive within theme environment while maintaining universal obstacle functionality, absolutely pure checkerboard background pattern with alternating light gray and white squares, completely isolated obstacle sprite on checkerboard transparency grid, zero environmental interference, clean sprite extraction with checkerboard background, optimal game asset format with checkerboard transparency indicator'
  },

  // 反向提示词模板
  negative: {
    character: '3D render, realistic style, photorealistic, low resolution, blurry, smooth gradients, modern UI elements, flat design, vector art, cartoon style, anime style, oversaturated colors, environmental objects, scenery, landscape, background elements, terrain, ground, floor, walls, buildings, architecture, decorative objects, props, furniture, plants, trees, rocks, stones, weapons on ground, items scattered, atmospheric effects, particles, dust, smoke, fog, weather effects, sky, clouds, sun, moon, stars, lighting fixtures, torches, lamps, shadows on background, reflections, water, fire effects, magical auras around environment, ornamental borders, frames, UI elements, health bars, menus, text overlays, multiple characters, character duplicates, front view, back view, three-quarter view, diagonal pose, close-up shots, partial body view, cropped limbs, cut-off head or feet, zoomed-in details, portrait mode, bust shot, headshot, torso only, legs only, arms only, incomplete body parts, off-center positioning, tilted composition, extreme angles, facing left direction, left-facing pose, looking left, turned left, background textures, surface patterns, environmental details, contextual elements, setting indicators, location markers, ambient objects, secondary elements, supporting props, background artifacts, environmental noise, visual clutter, non-character pixels, background interference, mixed elements, composite backgrounds, layered environments, depth elements, atmospheric layers, background gradients, environmental shadows, contextual lighting, scene elements, world objects, left side objects, right side objects, side elements, adjacent items, surrounding objects, flanking elements, peripheral objects, side decorations, lateral elements, horizontal companions, side-by-side objects, neighboring items, bordering elements, edge objects, margin elements, side interference, lateral noise, horizontal clutter, side distractions, peripheral interference, solid background colors, white background, colored backgrounds, background fills, opaque backgrounds, background contamination, background bleeding, edge artifacts, background noise, non-transparent areas, solid color fills, background gradients, background patterns',
    background: '3D render, realistic style, photorealistic, low resolution, blurry, smooth gradients, modern UI elements, flat design, vector art, characters, people, creatures, living beings, humanoid figures, animals, character silhouettes, organic life forms, human shadows, figure outlines, body shapes, limb suggestions, facial features, anthropomorphic elements, character equipment, weapons, armor pieces, clothing items, accessories',
    ground: '3D render, realistic style, photorealistic, low resolution, blurry, smooth gradients, modern UI elements, flat design, vector art, characters, people, creatures, living beings, humanoid figures, animals, character silhouettes, organic life forms, human shadows, figure outlines, body shapes, limb suggestions, facial features, anthropomorphic elements, character equipment, weapons, armor pieces, clothing items, accessories, environmental objects, surface elements, decorative items, props, vegetation, plants, trees, grass, flowers, roots, structures, buildings, architecture, atmospheric effects, particles, dust, smoke, fog, weather effects, sky elements, clouds, lighting fixtures, torches, lamps, shadows, reflections, water bodies, fire effects, magical elements, ornamental details, surface decorations, contextual objects, scene elements, world objects, environmental interference, background elements, scenery, landscape, complex geological formations, mineral veins, detailed stratification, intricate layering, elaborate earth composition, sophisticated subsurface materials, detailed underground layers, complex sediment deposits, intricate rock formations, elaborate mineral patterns, detailed geological structures, sophisticated layering systems, complex material compositions, intricate subsurface details, elaborate cross-sectional patterns, detailed internal structures, sophisticated material variations, complex thematic patterns, intricate depth effects, elaborate horizontal layering, detailed authentic appearances, sophisticated color variations, non-tileable patterns, irregular shapes, complex compositions, surface view, top-down view, aerial perspective, vertical cross-section, diagonal cross-section, angled cross-section, tilted perspective, rotated view, oblique angle, slanted view, inclined perspective, empty spaces, blank areas, transparent regions, void areas, unfilled sections, sparse coverage, incomplete filling, partial coverage, gaps in texture, hollow areas, vacant spaces, missing material, insufficient density, low coverage ratio, empty corners, blank edges, transparent borders, unfilled margins, sparse material distribution, incomplete saturation, partial material presence, checkerboard visibility, background showing through, transparent checkerboard pattern visible, empty checkerboard squares, unfilled checkerboard areas, checkerboard background bleeding through, visible transparency grid, exposed checkerboard pattern',
    obstacle: '3D render, realistic style, photorealistic, low resolution, blurry, smooth gradients, modern UI elements, flat design, vector art, characters, people, creatures, living beings, humanoid figures, animals, character silhouettes, organic life forms, human shadows, figure outlines, body shapes, limb suggestions, facial features, anthropomorphic elements, character equipment worn by characters, background elements, scenery, landscape, terrain, ground, floor, walls, buildings, architecture, atmospheric effects, particles, dust, smoke, fog, weather effects, sky, clouds, sun, moon, stars, lighting fixtures, torches, lamps, shadows on background, reflections, water, fire effects, magical auras around environment, multiple objects, object duplicates, complex compositions, layered environments, depth elements, environmental shadows, contextual lighting, scene elements, ANY perspective distortion, ANY depth perspective, ANY three-point perspective, ANY isometric view, ANY diagonal angles, ANY tilted perspective, ANY rotated view, ANY oblique angles, ANY slanted view, ANY inclined perspective, ANY angled projection, ANY perspective foreshortening, ANY angular distortion, ANY non-orthographic projection, ANY diagonal orientation, ANY tilted composition, ANY rotated perspective, ANY slanted orientation, ANY inclined angles, ANY perspective depth, ANY vanishing points, ANY foreshortened proportions, ANY angular viewpoints, ANY diagonal viewing angles, ANY tilted viewing perspective, ANY rotated camera angle, ANY oblique projection, ANY depth illusion, ANY dimensional perspective, ANY spatial depth, ANY perspective lines, ANY convergence points, ANY horizon lines, ANY eye-level perspective, ANY bird-eye view, ANY worm-eye view, ANY side angles, ANY corner views, ANY three-quarter views, ANY profile angles, ANY angled views, ANY perspective effects, ANY depth rendering, ANY 3D projection, ANY volumetric presentation, ANY spatial orientation, ANY dimensional rotation, ANY perspective transformation, theme-inconsistent elements, mismatched style elements, conflicting design themes, inappropriate thematic elements, out-of-place objects, style-breaking elements, thematic contradictions, design inconsistencies, visual style conflicts, inappropriate color schemes, mismatched aesthetic elements'
  }
} as const

/**
 * @name 预设游戏主题
 * @description 用于提供用户选择的默认游戏主题（包含简要描述作为提示词）
 */
export const PRESET_THEMES: Theme[] = [
  {
    id: 'fantasy',
    name: 'Fantasy',
    description: 'A fantasy world of magic, dragons, castles, and forests',
    characterImage: 'https://img.alicdn.com/imgextra/i2/O1CN01jUlQ0L237JvklbMar_!!6000000007208-2-tps-1328-1328.png',
    backgroundImage: 'https://img.alicdn.com/imgextra/i4/O1CN01DX2Y9722KlwmMkO6R_!!6000000007102-2-tps-1664-928.png',
    groundImage: 'https://img.alicdn.com/imgextra/i1/O1CN014B08X31Zmb9ZUdlHr_!!6000000003237-2-tps-1328-1328.png',
    obstacleImage: 'https://img.alicdn.com/imgextra/i2/O1CN01NKpF221RbahyffacB_!!6000000002130-2-tps-1328-1328.png',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: 'A sci-fi world of neon lights, machinery, and future cities',
    characterImage: 'https://img.alicdn.com/imgextra/i4/O1CN016rAWdt1UXsLJ4Qjsl_!!6000000002528-2-tps-1328-1328.png',
    backgroundImage: 'https://img.alicdn.com/imgextra/i1/O1CN01ZV3lei1UBtKaCzJNU_!!6000000002480-2-tps-1664-928.png',
    groundImage: 'https://img.alicdn.com/imgextra/i1/O1CN014B08X31Zmb9ZUdlHr_!!6000000003237-2-tps-1328-1328.png',
    obstacleImage: 'https://img.alicdn.com/imgextra/i2/O1CN01NKpF221RbahyffacB_!!6000000002130-2-tps-1328-1328.png',
  },
  {
    id: 'western-world',
    name: 'Western World',
    description: 'A wild west world of cowboys, saloons, desert landscapes, and frontier towns',
    characterImage: 'https://img.alicdn.com/imgextra/i4/O1CN01qxICQy1DqKq1mBrHk_!!6000000000267-2-tps-1328-1328.png',
    backgroundImage: 'https://img.alicdn.com/imgextra/i1/O1CN01pLhR7Q1XiMFoAjrej_!!6000000002957-2-tps-1664-928.png',
    groundImage: 'https://img.alicdn.com/imgextra/i1/O1CN014B08X31Zmb9ZUdlHr_!!6000000003237-2-tps-1328-1328.png',
    obstacleImage: 'https://img.alicdn.com/imgextra/i2/O1CN01NKpF221RbahyffacB_!!6000000002130-2-tps-1328-1328.png',
  },
  {
    id: 'underwater-world',
    name: 'Underwater World',
    description: 'A mysterious underwater world of coral reefs, deep sea creatures, and ancient underwater civilizations',
    characterImage: 'https://img.alicdn.com/imgextra/i4/O1CN01DCkIcD1oYbHjJTTuU_!!6000000005237-2-tps-1328-1328.png',
    backgroundImage: 'https://img.alicdn.com/imgextra/i2/O1CN01tN5Gsu216HnoGtIKd_!!6000000006935-2-tps-1664-928.png',
    groundImage: 'https://img.alicdn.com/imgextra/i1/O1CN014B08X31Zmb9ZUdlHr_!!6000000003237-2-tps-1328-1328.png',
    obstacleImage: 'https://img.alicdn.com/imgextra/i2/O1CN01NKpF221RbahyffacB_!!6000000002130-2-tps-1328-1328.png',
  }
] as const